volumes:
  db-crud:

services:
  postgres-db:
    container_name: embrapii
    image: postgres:14.13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-crud:/var/lib/postgresql